### ISSUE TITLE
Daftar artikel tidak ada di localhost

### ISSUE THREAD

**Issue by kresnasatya** [w3id/wwwid.org#10]
Halo mas, saya sudah mengikuti cara fork ini di sesi **Setup** namun tidak ada daftar artikel di halaman seperti gambar di bawah ini.

<img width="1552" alt="Screenshot 2020-01-18 at 3 54 28 PM" src="https://user-images.githubusercontent.com/11099186/72660638-61ea0780-3a0b-11ea-8555-5ffa61217d20.png">

Apakah ada pengaruhnya dengan versi hugo atau theme yang digunakan? Saya menggunakan hugo versi v0.62.0.

**Comment by tyohan** [comment]
@satyakresna tampaknya karena versi terbaru tidak kompatibel dengan theme yang ada. Barusan sudah update, termasuk Hugo terbaru. Silakan pull request dan pull submodule sesuai di readme.
