### ISSUE TITLE
[TANYA] Kenapa tidak menggunakan Netlify untuk deployment

### ISSUE THREAD

**Issue by kresnasatya** [w3id/wwwid.org#5]
Netlify memudahkan dalam urusan deployment layanan website statis seperti Hugo seperti yang tertera di sini: https://gohugo.io/hosting-and-deployment/hosting-on-netlify/. Kemudian sisanya tinggal custom domain saja. Website pribadi saya juga menggunakan hugo dan netlify untuk urusan deployment.

**Comment by tyohan** [comment]
Karena untuk Netlify cuma bisa personal, ga bisa organisasi kayak Github dan Travis. Jadi kalau ini nanti teman-teman lain bisa manage bareng. Kalau netlify saya harus ngasih akun untuk manage di sana.

**Comment by kresnasatya** [comment]
Oh begitu rupanya. Trims infonya mas.
